export const ChatConstants = {
    GET_ALL_CONNECTIONS_REQUEST: 'GET_ALL_CONNECTIONS_REQUEST',
    GET_ALL_CONNECTIONS_SUCCESS: 'GET_ALL_CONNECTIONS_SUCCESS',
    GET_ALL_CONNECTIONS_FAILE: 'GET_ALL_CONNECTIONS_FAILE',

    RECEIVE_MESSAGE_REQUEST: 'RECEIVE_MESSAGE_REQUEST',
    RECEIVE_MESSAGE_SUCCESS: 'RECEIVE_MESSAGE_SUCCESS',
    RECEIVE_MESSAGE_FAILE: 'RECEIVE_MESSAGE_FAILE',

    CREATE_CONVERSATION_REQUEST: 'CREATE_CONVERSATION_REQUEST',
    CREATE_CONVERSATION_SUCCESS: 'CREATE_CONVERSATION_SUCCESS',
    CREATE_CONVERSATION_FAILE: 'CREATE_CONVERSATION_FAILE',
}
