export const ChatConstants = {
    GET_ALL_CONNECTIONS_REQUEST: 'GET_ALL_CONNECTIONS_REQUEST',
    GET_ALL_CONNECTIONS_SUCCESS: 'GET_ALL_CONNECTIONS_SUCCESS',
    GET_ALL_CONNECTIONS_FAILE: 'GET_ALL_CONNECTIONS_FAILE',
    
    
}
