export const SearchConstants = {
    SEARCH_POST_REQUEST: 'SEARCH_POST_REQUEST',
    SEARCH_POST_SUCCESS: 'SEARCH_POST_SUCCESS',
    SEARCH_POST_FAILE: 'SEARCH_POST_FAILE',

    SEARCH_USER_REQUEST: 'SEARCH_USER_REQUEST',
    SEARCH_USER_SUCCESS: 'SEARCH_USER_SUCCESS',
    SEARCH_USER_FAILE: 'SEARCH_USER_FAILE',
}