export const PostConstants = {
    CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILE: 'CREATE_POST_FAILE',

    GET_NEW_FEED_REQUEST: 'GET_NEW_FEED_REQUEST',
    GET_NEW_FEED_SUCCESS: 'GET_NEW_FEED_SUCCESS',
    GET_NEW_FEED_FAILE: 'GET_NEW_FEED_FAILE',

}