export const PostConstants = {
    CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILE: 'CREATE_POST_FAILE',

    GET_NEW_FEED_REQUEST: 'GET_NEW_FEED_REQUEST',
    GET_NEW_FEED_SUCCESS: 'GET_NEW_FEED_SUCCESS',
    GET_NEW_FEED_FAILE: 'GET_NEW_FEED_FAILE',

    SET_COMMENT_REQUEST: 'SET_COMMENT_REQUEST',
    SET_COMMENT_SUCCESS: 'SET_COMMENT_SUCCESS',
    SET_COMMENT_FAILE: 'SET_COMMENT_FAILE',

    LIKE_POST_REQUEST: 'LIKE_POST_REQUEST',
    LIKE_POST_SUCCESS: 'LIKE_POST_SUCCESS',
    LIKE_POST_FAILE: 'LIKE_POST_FAILE',

    DISLIKE_POST_REQUEST: 'DISLIKE_POST_REQUEST',
    DISLIKE_POST_SUCCESS: 'DISLIKE_POST_SUCCESS',
    DISLIKE_POST_FAILE: 'DISLIKE_POST_FAILE',

}